services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: runtrack-postgres
    environment:
      - 'POSTGRES_DB=runtrack_db'
      - 'POSTGRES_USER=runner'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: 'redis:7-alpine'
    container_name: runtrack-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: